requires:
- category: "libs"
  name: "skalibs"
  version: ">=0"

env:
- MUSL_TARGET=x86_64-mocaccino-linux-musl
- MUSL_ARCH=x86
- MUSL_CPU=x86-64
- CFLAGS="-I/include -I/usr/include -static"
- LDFLAGS="-L/usr/lib/skalibs"
- CC="gcc"

package_dir: /void-runit
prelude:
- |
   luet install shells/bash && \
   luet uninstall utils/busybox-static && \
   luet install utils/coreutils && \
   ln -s /bin/bash /bin/sh && \
   mkdir -p /${PACKAGE_NAME} && \
   git clone https://github.com/void-linux/${PACKAGE_NAME} && cd ${PACKAGE_NAME} && git checkout -b build ${PACKAGE_VERSION}

steps:
- cd ${PACKAGE_NAME} && make -j8
- cd ${PACKAGE_NAME} && make DESTDIR=/${PACKAGE_NAME} install
- cd ${PACKAGE_NAME} && make install