requires:
- category: "libs"
  name: "skalibs"
  version: ">=0"
- category: "lang"
  name: "execline"
  version: ">=0"
env:
- MUSL_TARGET=x86_64-mocaccino-linux-musl
- MUSL_ARCH=x86
- MUSL_CPU=x86-64
- CFLAGS="-I/include -I/usr/include -static"

package_dir: /ncurses
prelude:
- |
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   mkdir -p /${PACKAGE_NAME} && \
   git clone https://github.com/mirror/${PACKAGE_NAME} && cd ${PACKAGE_NAME} && git checkout -b build v${PACKAGE_VERSION}

steps:
- cd ${PACKAGE_NAME} && ./configure --prefix=/usr -enable-termcap
- cd ${PACKAGE_NAME} && make -j8
- cd ${PACKAGE_NAME} && make DESTDIR=/${PACKAGE_NAME} install
- cd ${PACKAGE_NAME} && make install