requires:
- category: "libs"
  name: "skalibs"
  version: ">=0"
- category: "lang"
  name: "execline"
  version: ">=0"
- category: "init"
  name: "s6"
  version: ">=0"
- category: "init"
  name: "s6-rc"
  version: ">=0"
env:
- CFLAGS="-I/include -I/usr/include -static"
- LDFLAGS="-L/usr/lib/execline -L/usr/lib/skalibs -L/usr/lib/s6"

package_dir: /lowdown
prelude:
- |
   mkdir -p /${PACKAGE_NAME} && \
   git clone https://github.com/kristapsdz/${PACKAGE_NAME} && cd ${PACKAGE_NAME} && git checkout -b build VERSION_0_7_1

steps:
- cd ${PACKAGE_NAME} && ./configure
- cd ${PACKAGE_NAME} && make -j8
- cd ${PACKAGE_NAME} && make DESTDIR=/${PACKAGE_NAME} install
- cd ${PACKAGE_NAME} && make install
