requires:
- category: "libs"
  name: "skalibs"
  version: ">=0"
- category: "lang"
  name: "execline"
  version: ">=0"

env:
- MUSL_TARGET=x86_64-mocaccino-linux-musl
- MUSL_ARCH=x86
- MUSL_CPU=x86-64
- CFLAGS="-I/include -I/usr/include -static"
- LDFLAGS="-L/usr/lib/execline -L/usr/lib/skalibs"

package_dir: /openssh
prelude:
- |
   luet install utils/autoconf development/automake development/m4 libs/libressl && \
   mkdir -p /${PACKAGE_NAME} && \
   git clone https://github.com/${PACKAGE_NAME}/${PACKAGE_NAME}-portable ${PACKAGE_NAME} && cd ${PACKAGE_NAME} && git checkout -b build V_8_3_P1

steps:
- cd ${PACKAGE_NAME} && autoreconf
- cd ${PACKAGE_NAME} && ./configure --prefix=/usr
- cd ${PACKAGE_NAME} && make -j8
- cd ${PACKAGE_NAME} && make DESTDIR=/${PACKAGE_NAME} install-nokeys
- cd ${PACKAGE_NAME} && make install-nokeys
