image: "quay.io/mocaccino/micro-toolchain:latest"
prelude:
- |
   luet install \
   utils/autoconf utils/curl development/make libs/zlib vcs/git development/automake development/pkg-config development/m4
