image: "quay.io/mocaccino/extra"
prelude:
- luet install development/make lang/go vcs/git
- git clone https://github.com/MottainaiCI/lxd-compose.git
env:
- GIT_HASH=2bf84cba72075e6522ab8d5a739eb2307fca104b
steps:
- cd lxd-compose && git checkout "${GIT_HASH}" && make build && mv lxd-compose /usr/bin/lxd-compose
includes:
- /usr/bin/lxd-compose
