image: "quay.io/mocaccino/extra"
prelude:
- luet install development/make lang/go vcs/git
- git clone https://github.com/MottainaiCI/lxd-compose.git
env:
- GIT_HASH=1ccec0b50784e8f63ccba71294b982341d9f3ddb
steps:
- cd lxd-compose && git checkout "${GIT_HASH}" && make build && mv lxd-compose /usr/bin/lxd-compose
includes:
- /usr/bin/lxd-compose
