requires:
- category: "development"
  name: "toolchain"
  version: ">=0"

env:
- MUSL_TARGET=x86_64-mocaccino-linux-musl
- MUSL_ARCH=x86
- MUSL_CPU=x86-64

package_dir: /bison
prelude:
- | 
   luet install utils/autoconf utils/curl libs/zlib vcs/git development/automake development/pkg-config development/m4 \
   development/make system/musl-toolchain && \
   luet install libs/gettext-tools && \
   curl -L https://ftp.gnu.org/gnu/bison/bison-${PACKAGE_VERSION}.tar.xz -o bison-${PACKAGE_VERSION}.tar.xz && \
   tar -xvf bison-${PACKAGE_VERSION}.tar.xz -C ./ && mv bison-${PACKAGE_VERSION} ${PACKAGE_NAME} && \
   mkdir -p /${PACKAGE_NAME}

steps:
- |
   cd ${PACKAGE_NAME} && \
   ./configure --prefix=/usr && \
   make DESTDIR=/${PACKAGE_NAME} && \
   make DESTDIR=/${PACKAGE_NAME} install && make install
