requires:
- category: "libs"
  name: "skalibs"
  version: ">=0"

env:
- MUSL_TARGET=x86_64-mocaccino-linux-musl
- MUSL_ARCH=x86
- MUSL_CPU=x86-64
- CFLAGS="-I/include -I/usr/include -static"
- LDFLAGS="-L/usr/lib/skalibs"
- CC="gcc"

package_dir: /k3s
prelude:
- |
   mkdir -p /${PACKAGE_NAME}/etc/sv && \
   mkdir -p /${PACKAGE_NAME}/etc/runit/runsvdir

steps:
- cp -rfv services/* /${PACKAGE_NAME}/etc/sv/
- cp -rfv runlevel/* /${PACKAGE_NAME}/etc/runit/runsvdir
- mkdir -p /${PACKAGE_NAME}/var/log/k3s
