image: "quay.io/mocaccino/micro-toolchain:develop"


env:
- MUSL_TARGET=x86_64-mocaccino-linux-musl
- MUSL_ARCH=x86
- MUSL_CPU=x86-64
- DISABLE_WARN_OUTSIDE_CONTAINER=1
- GOPATH=/go

package_dir: /docker-cli
prelude:
- |
   luet install shells/bash development/make utils/ca-certificates libs/libressl vcs/git lang/go && \
   git clone https://github.com/docker/cli.git && \
   cd cli && git checkout -b build v${PACKAGE_VERSION} && cd .. && \
   mkdir -p $GOPATH/src && \
   mv cli/vendor/* $GOPATH/src && \
   mv cli $GOPATH/src/github.com/docker


steps:
- | 
   mkdir -p /docker-cli/usr/bin && \
   cd $GOPATH/src/github.com/docker/cli && make binary && \
   mv build/docker-linux-amd64 /docker-cli/usr/bin/docker
