requires:
- name: libxslt
  category: libs
  version: ">=0"
env:
- MUSL_TARGET=x86_64-mocaccino-linux-musl
- MUSL_ARCH=x86
- MUSL_CPU=x86-64
- CFLAGS="-I/include -I/usr/include -static"
- LDFLAGS="-L/usr/lib/execline -L/usr/lib/skalibs"

package_dir: /eudev
prelude:
- |
   luet install utils/autoconf development/automake development/m4 development/gperf development/pkg-config development/libtool && \
   mkdir -p /${PACKAGE_NAME} && \
   git clone https://github.com/gentoo/${PACKAGE_NAME} && cd ${PACKAGE_NAME} && git checkout -b build v${PACKAGE_VERSION}

steps:
- cd ${PACKAGE_NAME} && ./autogen.sh
- cd ${PACKAGE_NAME} && ./configure --prefix=/usr --bindir=/bin --includedir=/usr/include --libdir=/usr/lib	--with-rootlibexecdir=/lib/udev --sysconfdir=/etc --enable-static --enable-split-usr --with-rootprefix= --with-rootrundir=/run
- cd ${PACKAGE_NAME} && make -j8
- cd ${PACKAGE_NAME} && make DESTDIR=/${PACKAGE_NAME} install
- cd ${PACKAGE_NAME} && make install
